const COINS=[{id:"bitcoin",symbol:"BTC",name:"Bitcoin"},{id:"ethereum",symbol:"ETH",name:"Ethereum"},{id:"solana",symbol:"SOL",name:"Solana"}];
const state={selectedCoin:"bitcoin",selectedDays:30,chart:null,marketData:[],chartCache:{},chartRequestToken:0};
const els={coinGrid:document.getElementById("coinGrid"),chartTitle:document.getElementById("chartTitle"),refreshBtn:document.getElementById("refreshBtn"),lastUpdated:document.getElementById("lastUpdated"),selectedAssetName:document.getElementById("selectedAssetName"),signalPill:document.getElementById("signalPill"),actionBias:document.getElementById("actionBias"),buyScore:document.getElementById("buyScore"),sellScore:document.getElementById("sellScore"),change24h:document.getElementById("change24h"),guidanceText:document.getElementById("guidanceText"),metricPrice:document.getElementById("metricPrice"),metricMarketCap:document.getElementById("metricMarketCap"),metricVolume:document.getElementById("metricVolume"),metricRank:document.getElementById("metricRank"),timeframeButtons:Array.from(document.querySelectorAll(".time-buttons button")),chartLoading:document.getElementById("chartLoading"),chartCanvas:document.getElementById("chart")};
const chartKey=(coinId=state.selectedCoin,days=state.selectedDays)=>`${coinId}_${days}`;
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const pctChange=(a,b)=>!a||b==null?0:((b-a)/a)*100;
const fmtMoney=(v,compact=false)=>v==null?"--":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:compact?"compact":"standard",maximumFractionDigits:v>=1000?0:2}).format(v);
const fmtPct=v=>v==null?"--":`${v>0?"+":""}${v.toFixed(2)}%`;
const selectedMeta=()=>COINS.find(c=>c.id===state.selectedCoin)||COINS[0];
const selectedCoinData=()=>state.marketData.find(c=>c.id===state.selectedCoin);
function showChartLoading(show){els.chartLoading.classList.toggle("hidden",!show)}
async function fetchMarketData(){const ids=COINS.map(c=>c.id).join(",");const res=await fetch(`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=${ids}&price_change_percentage=24h`,{cache:"no-store"});if(!res.ok)throw new Error("market");return await res.json()}
async function fetchChartData(coinId,days){const res=await fetch(`https://api.coingecko.com/api/v3/coins/${coinId}/market_chart?vs_currency=usd&days=${days}`,{cache:"no-store"});if(!res.ok)throw new Error("chart");const data=await res.json();state.chartCache[chartKey(coinId,days)]=data;return data}
function buildLabels(prices,days){return prices.map(([ts])=>{const d=new Date(ts);if(+days===1)return d.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"});if(+days===7)return d.toLocaleDateString([], {weekday:"short",day:"2-digit"});return d.toLocaleDateString([], {day:"2-digit",month:"short"})})}
function stddev(vals){if(!vals||vals.length<2)return 0;const mean=vals.reduce((a,b)=>a+b,0)/vals.length;return Math.sqrt(vals.reduce((a,v)=>a+(v-mean)**2,0)/vals.length)}
function computeChartStats(coinId){const d7=state.chartCache[chartKey(coinId,7)]?.prices||[];const d30=state.chartCache[chartKey(coinId,30)]?.prices||[];const p7=d7.map(p=>p[1]);const p30=d30.map(p=>p[1]);const current7=p7.at(-1),current30=p30.at(-1);const change7=pctChange(p7[0],current7),change30=pctChange(p30[0],current30);const high30=p30.length?Math.max(...p30):null;const low30=p30.length?Math.min(...p30):null;const distFrom30High=high30&&current30?((current30-high30)/high30)*100:0;const distFrom30Low=low30&&current30?((current30-low30)/low30)*100:0;const sampled=[];if(p30.length>1){const step=Math.max(1,Math.floor(p30.length/30));for(let i=step;i<p30.length;i+=step){sampled.push(pctChange(p30[i-step],p30[i]))}}return {has7:d7.length>1,has30:d30.length>1,change7,change30,distFrom30High,distFrom30Low,volatility:stddev(sampled)}}
function getScores(coin){const change24=coin?.price_change_percentage_24h??0;const s=computeChartStats(coin.id);let buy=50,sell=50;if(change24<=-8)buy+=16;else if(change24<=-4)buy+=10;else if(change24>=8)sell+=18;else if(change24>=4)sell+=10;if(s.has7){if(s.change7<=-12)buy+=14;else if(s.change7<=-6)buy+=8;else if(s.change7>=12)sell+=14;else if(s.change7>=6)sell+=8}if(s.has30){if(s.distFrom30High<=-18)buy+=14;else if(s.distFrom30High<=-10)buy+=8;if(s.distFrom30Low<=6)buy+=8;else if(s.distFrom30Low>=24)sell+=6;if(s.change30>=20)sell+=10;else if(s.change30<=-15)buy+=10}if(s.volatility>=8){buy-=8;sell+=4}else if(s.volatility>=5){buy-=4;sell+=2}else if(s.volatility<=2.5){buy+=3}if((coin?.market_cap_rank??999)<=10)buy+=4;if((coin?.total_volume??0)>1_000_000_000)buy+=3;buy=clamp(Math.round(buy),0,100);sell=clamp(Math.round(sell),0,100);if(buy>sell)sell=clamp(Math.round(sell-(buy-sell)*0.25),0,100);else if(sell>buy)buy=clamp(Math.round(buy-(sell-buy)*0.25),0,100);return {buy,sell,stats:s}}
const signalLabel=s=>s.buy>=72?"Buy Zone":s.buy>=60?"Watch for Entry":s.sell>=72?"Take Profit":s.sell>=60?"Reduce Risk":"Hold / Neutral";
const actionBias=s=>s.buy-s.sell>=12?"Leaning Buy":s.sell-s.buy>=12?"Leaning Sell":"Balanced";
function guidance(coin,s){if(s.buy>=72)return `${coin.name} is trading weak versus its recent range, which gives it a stronger buy score. It is well below its recent highs and may be entering a more attractive entry zone.`;if(s.buy>=60)return `${coin.name} is starting to look more interesting on weakness. It is softer than its recent range, but not at an extreme level yet.`;if(s.sell>=72)return `${coin.name} looks extended after recent strength. The model sees it as more of a take-profit area than a fresh buy.`;if(s.sell>=60)return `${coin.name} is running hot relative to its recent range. Waiting for a cooler entry may be safer than chasing it here.`;return `${coin.name} sits in a more neutral zone right now. Recent momentum and range position are mixed, so patience may be the better play.`}
function updateSelectedPanels(){const meta=selectedMeta(),coin=selectedCoinData();if(!coin)return;const s=getScores(coin),chg=coin.price_change_percentage_24h??0;els.selectedAssetName.textContent=meta.name;els.signalPill.textContent=signalLabel(s);els.actionBias.textContent=actionBias(s);els.buyScore.textContent=`${s.buy}/100`;els.sellScore.textContent=`${s.sell}/100`;els.change24h.textContent=fmtPct(chg);els.change24h.className="insight-value "+(chg>0?"positive":chg<0?"negative":"neutral");els.guidanceText.textContent=guidance(coin,s);els.metricPrice.textContent=fmtMoney(coin.current_price);els.metricMarketCap.textContent=fmtMoney(coin.market_cap,true);els.metricVolume.textContent=fmtMoney(coin.total_volume,true);els.metricRank.textContent="#"+(coin.market_cap_rank??"--");els.chartTitle.textContent=`${meta.symbol} Chart`}
function renderCoinCards(){els.coinGrid.innerHTML="";for(const coin of state.marketData){const s=getScores(coin),active=coin.id===state.selectedCoin,up=(coin.price_change_percentage_24h??0)>=0;const card=document.createElement("button");card.type="button";card.className=`coin-card${active?" active":""}`;card.innerHTML=`<div class="coin-top"><h3>${coin.symbol.toUpperCase()}</h3><span class="status-pill">${signalLabel(s)}</span></div><div class="price">${fmtMoney(coin.current_price)}</div><div class="${up?"positive":"negative"}">${fmtPct(coin.price_change_percentage_24h??0)}</div><div class="mini-meta">Buy ${s.buy}/100 · Sell ${s.sell}/100</div>`;card.addEventListener("click",async()=>{state.selectedCoin=coin.id;renderCoinCards();updateSelectedPanels();await renderSelectedChart(true);prefetchCoinRanges(coin.id)});els.coinGrid.appendChild(card)}}
function createGradient(ctx){const g=ctx.createLinearGradient(0,0,0,320);g.addColorStop(0,"rgba(176, 38, 255, 0.34)");g.addColorStop(1,"rgba(176, 38, 255, 0.02)");return g}
function renderChartFromData(chartData){const prices=chartData?.prices||[];const labels=buildLabels(prices,state.selectedDays);const values=prices.map(p=>p[1]);const ctx=els.chartCanvas.getContext("2d");if(state.chart)state.chart.destroy();state.chart=new Chart(ctx,{type:"line",data:{labels,datasets:[{data:values,borderColor:"#b026ff",backgroundColor:createGradient(ctx),borderWidth:3,tension:0.32,fill:true,pointRadius:0,pointHoverRadius:4,pointHoverBackgroundColor:"#fff",pointHoverBorderColor:"#b026ff",pointHoverBorderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,animation:false,interaction:{intersect:false,mode:"index"},plugins:{legend:{display:false},tooltip:{backgroundColor:"#0f0f14",titleColor:"#fff",bodyColor:"#d4d4d8",borderColor:"rgba(176, 38, 255, 0.35)",borderWidth:1,displayColors:false,callbacks:{label:c=>`$${c.parsed.y.toLocaleString(undefined,{maximumFractionDigits:2})}`}}},scales:{x:{ticks:{color:"#a1a1aa",maxTicksLimit:8},grid:{color:"rgba(255,255,255,0.04)"},border:{display:false}},y:{ticks:{color:"#a1a1aa",callback:v=>"$"+Number(v).toLocaleString()},grid:{color:"rgba(255,255,255,0.04)"},border:{display:false}}}}})}
async function renderSelectedChart(forceRefresh=false){const token=++state.chartRequestToken;const key=chartKey();const cached=state.chartCache[key];if(cached)renderChartFromData(cached);showChartLoading(!cached);if(!cached||forceRefresh){try{const data=await fetchChartData(state.selectedCoin,state.selectedDays);if(token!==state.chartRequestToken)return;renderChartFromData(data);renderCoinCards();updateSelectedPanels()}catch(e){console.error(e);if(!cached)els.lastUpdated.textContent="Last updated: chart delayed"}finally{if(token===state.chartRequestToken)showChartLoading(false)}}else{showChartLoading(false);fetchChartData(state.selectedCoin,state.selectedDays).then(data=>{if(token===state.chartRequestToken){renderChartFromData(data);renderCoinCards();updateSelectedPanels()}}).catch(()=>{})}}
async function loadMarket(){try{state.marketData=await fetchMarketData();renderCoinCards();updateSelectedPanels();els.lastUpdated.textContent=`Last updated: ${new Date().toLocaleTimeString()}`}catch(e){console.error(e);els.lastUpdated.textContent="Last updated: delayed"}}
function bindTimeframes(){for(const btn of els.timeframeButtons){btn.addEventListener("click",async()=>{for(const b of els.timeframeButtons)b.classList.remove("active");btn.classList.add("active");state.selectedDays=Number(btn.dataset.days);await renderSelectedChart(true)})}}
function prefetchCoinRanges(coinId){[7,30].forEach(days=>{const key=chartKey(coinId,days);if(!state.chartCache[key])fetchChartData(coinId,days).then(()=>{renderCoinCards();if(coinId===state.selectedCoin)updateSelectedPanels()}).catch(()=>{})})}
async function prefetchAllScores(){const jobs=[];for(const coin of COINS){for(const days of [7,30]){const key=chartKey(coin.id,days);if(!state.chartCache[key])jobs.push(fetchChartData(coin.id,days).catch(()=>null))}}if(jobs.length){await Promise.allSettled(jobs);renderCoinCards();updateSelectedPanels()}}
async function init(){bindTimeframes();els.refreshBtn.addEventListener("click",async()=>{await loadMarket();await renderSelectedChart(true)});await loadMarket();await renderSelectedChart(true);prefetchCoinRanges(state.selectedCoin);prefetchAllScores();setInterval(async()=>{await loadMarket();await renderSelectedChart(false)},30000)}
init();
